<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers all the WordPress packages scripts that are in the standardized
 * `build/` location.
 *
 * @param WP_Scripts $scripts WP_Scripts instance (passed by reference).
 *
 * @since 4.5.0
 *
 */

if ( ! function_exists( 'novablocks_register_packages_scripts' ) ) {
	function novablocks_register_packages_scripts() {

		foreach ( glob( novablocks_get_plugin_path() . 'build/*/index.js' ) as $path ) {
			// Prefix `wp-` to package directory to get script handle.
			// For example, `…/build/a11y/index.js` becomes `wp-a11y`.
			$handle = 'novablocks-' . basename( dirname( $path ) );

			// Replace `.js` extension with `.asset.php` to find the generated dependencies file.
			$asset_file   = substr( $path, 0, - 3 ) . '.asset.php';
			$asset        = file_exists( $asset_file )
				? require( $asset_file )
				: null;
			$dependencies = isset( $asset['dependencies'] ) ? $asset['dependencies'] : array();
			$version      = isset( $asset['version'] ) ? $asset['version'] : filemtime( $path );

			// Add dependencies that cannot be detected and generated by build tools.

			// Get the path from Gutenberg directory as expected by `novablocks_url`.
			$novablocks_path = substr( $path, strlen( novablocks_get_plugin_path() ) );

			wp_enqueue_script(
				$handle,
				novablocks_get_plugin_url() . '/' . $novablocks_path ,
				$dependencies,
				$version,
				true
			);
		}
	}
}
add_action( 'enqueue_block_editor_assets', 'novablocks_register_packages_scripts' );
