const presets = [
  {
    label: 'L27: Brancusi',
    value: 'tear2down7',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 6,
      gridcolumns: 6,
      gridrows: 6,
      featuresize: 4,
      featureposition: 1,
      fragmentation: 1,
      imageweightleft: 1,
      imageweightright: 2,
      metadetailsleft: 10,
      metadetailsright: 6,
      boostfeature: false,
      subfeature: true,
      balancemdandiw: false,
      hierarchycrossing: 30,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L47: Kafka',
    value: 'tear4down7',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 6,
      gridcolumns: 12,
      gridrows: 8,
      featuresize: 7,
      featureposition: 3,
      fragmentation: 0,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 0,
      metadetailsright: 10,
      boostfeature: true,
      subfeature: true,
      balancemdandiw: false,
      hierarchycrossing: 153,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L13: Aristotle',
    value: 'tear1down3',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 6,
      gridcolumns: 5,
      gridrows: 4,
      featuresize: 2,
      featureposition: 2,
      fragmentation: 0,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 6,
      metadetailsright: 3,
      boostfeature: false,
      subfeature: false,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L19: Nietzsche',
    value: 'tear1down9',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 11,
      gridcolumns: 6,
      gridrows: 5,
      featuresize: 3,
      featureposition: 2,
      fragmentation: 2,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 0,
      metadetailsright: 0,
      boostfeature: false,
      subfeature: true,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L23: Popper',
    value: 'tear1down9bis',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 11,
      gridcolumns: 7,
      gridrows: 5,
      featuresize: 3,
      featureposition: 3,
      fragmentation: 2,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 0,
      metadetailsright: 0,
      boostfeature: false,
      subfeature: true,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      containerHeight: 45,
      headerPosition: 0,
    }
  },
  {
    label: 'L10: Tolstoy',
    value: 'tear1down0',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 10,
      gridcolumns: 10,
      gridrows: 6,
      featuresize: 3,
      featureposition: 6,
      fragmentation: 0,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 0,
      metadetailsright: 0,
      boostfeature: false,
      subfeature: false,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L15: Asimov',
    value: 'tear1down5',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 7,
      gridcolumns: 6,
      gridrows: 6,
      featuresize: 2,
      featureposition: 4,
      fragmentation: 0,
      imageweightleft: 8,
      imageweightright: 2,
      metadetailsleft: 7,
      metadetailsright: 2,
      boostfeature: false,
      subfeature: false,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L45: Orwell',
    value: 'tear4down5',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 13,
      gridcolumns: 8,
      gridrows: 6,
      featuresize: 4,
      featureposition: 1,
      fragmentation: 2,
      imageweightleft: 8,
      imageweightright: 8,
      metadetailsleft: 7,
      metadetailsright: 2,
      boostfeature: false,
      subfeature: false,
      balancemdandiw: false,
      hierarchycrossing: 120,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L12: Dostoevsky',
    value: 'tear1down2',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 7,
      gridcolumns: 6,
      gridrows: 4,
      featuresize: 3,
      featureposition: 1,
      fragmentation: 2,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 7,
      metadetailsright: 0,
      boostfeature: false,
      subfeature: false,
      balancemdandiw: false,
      hierarchycrossing: 50,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L32: Eliade',
    status: 'development',
    value: 'tear3down2',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 8,
      gridcolumns: 4,
      gridrows: 8,
      featuresize: 2,
      featureposition: 2,
      fragmentation: 0,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 0,
      metadetailsright: 3,
      boostfeature: false,
      subfeature: true,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L30: Tolkien',
    value: 'tear3down0',
    preset: {
      layoutStyle: 'parametric',
      postsToShow: 5,
      gridcolumns: 4,
      gridrows: 8,
      featuresize: 2,
      featureposition: 2,
      fragmentation: 0,
      imageweightleft: 1,
      imageweightright: 0,
      metadetailsleft: 0,
      metadetailsright: 3,
      boostfeature: false,
      subfeature: true,
      balancemdandiw: false,
      hierarchycrossing: 0,
      flipcolsrows: false,
      headerPosition: 0,
    }
  },
  {
    label: 'L03: Dumas',
    value: 'tear0down3',
    preset: {
      layoutStyle: 'classic',
      postsToShow: 6,
      columns: 3,
    }
  }
];

export default presets;
